"""Shared data models for the baseline legal debate system."""

from __future__ import annotations

from datetime import datetime, timezone

# Python 3.10 compatibility: UTC alias
UTC = timezone.utc
from typing import Any, Literal

from pydantic import BaseModel, Field


class CaseProfile(BaseModel):
    """Normalized input case for ViLQA-style extractive legal QA."""

    case_id: str
    case_type: str = "legal_qa"
    context: str
    question: str
    answer: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def retrieval_query(self) -> str:
        """Text used by retrieval modules in later phases."""

        return f"{self.question}\n\n{self.context[:1000]}"

    def agent_view(self) -> dict[str, Any]:
        """Return case fields visible to agents, excluding the gold answer."""

        return {
            "case_id": self.case_id,
            "case_type": self.case_type,
            "context": self.context,
            "question": self.question,
            "metadata": self.metadata,
        }


class EvidenceDocument(BaseModel):
    """Legal evidence returned by the retrieval layer."""

    doc_id: str
    text: str
    source: str
    score: float | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class MemoryContext(BaseModel):
    """Past memory retrieved before debate starts."""

    regulations: list[dict[str, Any]] = Field(default_factory=list)
    experiences: list[dict[str, Any]] = Field(default_factory=list)
    cases: list[dict[str, Any]] = Field(default_factory=list)


AgentRole = Literal[
    "proponent",
    "opponent",
    "judge",
    "prosecutor",
    "defense",
    "defendant",
]


class AgentOutput(BaseModel):
    """Output generated by a debate-side or courtroom agent."""

    role: AgentRole
    round_index: int
    private_strategy: str
    public_argument: str
    evidence_ids: list[str] = Field(default_factory=list)
    memory_ids: list[str] = Field(default_factory=list)


class BeliefState(BaseModel):
    """Judge state after a debate turn."""

    round_index: int
    prediction: str
    confidence: float = Field(ge=0.0, le=100.0)
    reasoning: str


class Verdict(BaseModel):
    """Final judge decision."""

    prediction: str
    answer: str | None = None
    confidence: float = Field(ge=0.0, le=100.0)
    reasoning: str
    cited_evidence_ids: list[str] = Field(default_factory=list)


class EvalResult(BaseModel):
    """Multi-dimensional evaluation placeholder for later phases."""

    exact_match: float | None = None
    f1: float | None = None
    legal_accuracy: float | None = None
    argument_quality: float | None = None
    logical_consistency: float | None = None
    notes: str | None = None


class PredictionRecord(BaseModel):
    """Single prediction row saved by batch experiments."""

    case_id: str
    split: str
    method: str
    question: str
    gold_answer: str
    predicted_answer: str
    exact_match: float
    f1: float
    output_path: str | None = None


JudgeControlAction = Literal[
    "call_proponent",
    "call_opponent",
    "ask_question",
    "request_closing",
    "end_debate",
]


class JudgeControlDecision(BaseModel):
    """Next-step decision issued by the presiding judge."""

    action: JudgeControlAction
    message: str = ""
    confidence: float = 50.0
    reasoning: str = ""


class DebateResult(BaseModel):
    """Complete result artifact for one debate."""

    case_id: str
    legal_evidence: list[EvidenceDocument] = Field(default_factory=list)
    memory_context: MemoryContext = Field(default_factory=MemoryContext)
    transcript: list[AgentOutput] = Field(default_factory=list)
    belief_history: list[BeliefState] = Field(default_factory=list)
    verdict: Verdict | None = None
    evaluation: EvalResult | None = None
    created_at: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())


class EvidenceItem(BaseModel):
    """Structured evidence item for courtroom LJP cases."""

    evidence_id: str
    text: str
    source_type: str = "document"
    metadata: dict[str, Any] = Field(default_factory=dict)


class Testimony(BaseModel):
    """Witness or party testimony in a courtroom case."""

    speaker: str
    text: str
    role: str = "witness"
    metadata: dict[str, Any] = Field(default_factory=dict)


class JudgmentGroundTruth(BaseModel):
    """Gold judgment labels for LJP evaluation."""

    charge: str
    articles: list[str] = Field(default_factory=list)
    sentence: str
    reasoning: str | None = None


class CourtCase(BaseModel):
    """Courtroom judgment prediction case with facts, evidence, and testimonies."""

    case_id: str
    case_type: str = "courtroom_ljp"
    facts: str
    evidence: list[EvidenceItem] = Field(default_factory=list)
    testimonies: list[Testimony] = Field(default_factory=list)
    ground_truth: JudgmentGroundTruth | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    def agent_view(self) -> dict[str, Any]:
        """Return case fields visible to agents, excluding gold judgment."""

        return {
            "case_id": self.case_id,
            "case_type": self.case_type,
            "facts": self.facts,
            "evidence": [item.model_dump() for item in self.evidence],
            "testimonies": [item.model_dump() for item in self.testimonies],
            "metadata": self.metadata,
        }

    def to_case_profile(self) -> CaseProfile:
        """Adapt a courtroom case into the Phase 1 CaseProfile container."""

        evidence_lines = [
            f"- [{item.evidence_id}] ({item.source_type}) {item.text}"
            for item in self.evidence
        ]
        testimony_lines = [
            f"- {item.speaker} ({item.role}): {item.text}"
            for item in self.testimonies
        ]
        context_parts = [f"Facts:\n{self.facts}"]
        if evidence_lines:
            context_parts.append("Evidence:\n" + "\n".join(evidence_lines))
        if testimony_lines:
            context_parts.append("Testimonies:\n" + "\n".join(testimony_lines))

        gold_sentence = self.ground_truth.sentence if self.ground_truth else None
        return CaseProfile(
            case_id=self.case_id,
            case_type=self.case_type,
            context="\n\n".join(context_parts),
            question="Predict charge, applicable articles, and sentence for this case.",
            answer=gold_sentence,
            metadata={
                **self.metadata,
                "courtroom_case": True,
                "gold_charge": self.ground_truth.charge if self.ground_truth else None,
                "gold_articles": (
                    list(self.ground_truth.articles) if self.ground_truth else []
                ),
            },
        )


class LegalJudgment(BaseModel):
    """Structured legal judgment prediction for courtroom LJP."""

    charge: str
    articles: list[str] = Field(default_factory=list)
    sentence: str
    reasoning: str
    confidence: float = Field(default=50.0, ge=0.0, le=100.0)
    cited_evidence_ids: list[str] = Field(default_factory=list)


class LJPEvalResult(BaseModel):
    """Evaluation metrics for legal judgment prediction."""

    charge_accuracy: float | None = None
    article_accuracy: float | None = None
    sentence_mae_years: float | None = None
    sentence_rmse_years: float | None = None
    sentence_bucket_accuracy: float | None = None
    citation_validity: float | None = None
    hallucination_rate: float | None = None
    objectivity: float | None = None
    logic_score: float | None = None
    citation_score: float | None = None
    notes: str | None = None


class CourtroomResult(BaseModel):
    """Complete artifact for a courtroom session."""

    case_id: str
    legal_evidence: list[EvidenceDocument] = Field(default_factory=list)
    memory_context: MemoryContext = Field(default_factory=MemoryContext)
    transcript: list[AgentOutput] = Field(default_factory=list)
    belief_history: list[BeliefState] = Field(default_factory=list)
    phases_completed: list[str] = Field(default_factory=list)
    deliberation: str | None = None
    verdict: Verdict | None = None
    legal_judgment: LegalJudgment | None = None
    evaluation: LJPEvalResult | None = None
    created_at: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_debate_result(self) -> DebateResult:
        """Backward-compatible view for Phase 1 artifact writers."""

        return DebateResult(
            case_id=self.case_id,
            legal_evidence=self.legal_evidence,
            memory_context=self.memory_context,
            transcript=self.transcript,
            belief_history=self.belief_history,
            verdict=self.verdict,
            evaluation=None,
            created_at=self.created_at,
        )
